### ISSUE TITLE
Drive train

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2019#11]
Implement the primary teleop drive train command.

Consider using feedback-based control (for example, speed control) rather than the straightforward power control that's usually implemented.  This would consist, for example, of using a PID controller to regulate the drive motor speed rather than directly regulating drive motor power, as a function of joystick input.  In theory, this will give the driver more precise control at low speeds, since the robot will respond directly to speed command rather than the driver having to vary the power level to achieve the desired speed.  At low speeds and especially when stopped, controlling speed manually can be difficult due to friction/[stiction](https://en.wikipedia.org/wiki/Stiction), etc.

**Comment by zerovectorspace** [comment]
Implementing this would require phasing out the `DifferentialDrive` object that holds the `WPI_TalonSRX` or `SpeedControllerGroup` objects. This is due to requiring a manual implementation of the `DifferentialDrive.tankDrive()` method (i.e. we need to be able to use `WPI_TalonSRX.set( ControlMode mode, double value)`). In effect, we would be running the motor controllers manually.

We can use the code from `DifferentialDrive.tankDrive()` as a basis: [DifferentialDrive API](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java)

Some caveats:
- if we want to allow switching of control styles (e.g. tank / arcade / cheesy), we would need to re-implement each of these using our speed control scheme for consistency.
- We lose the inherited `MotorSafety`. We could get around this by using the same inheritance chain as `DifferentialDrive` and just implementing what we need (i.e. Copy and paste `DifferentialDrive` class and rename it `FlapjackDrive`).

**Comment by jtechau** [comment]
This warrants some research.  Since the `DifferentialDrive` class can provide a set point to the Talon via `WPI_TalonSRX.set()`, the Talon might just need to be pre-configured into `Velocity` control mode.  If that's the case, `DifferentialDrive` won't need to know or care which control mode the Talon is in.

I can think of at least a couple reasons this might not work, so we need to experiment and verify.

**Comment by zerovectorspace** [comment]
Lines #349 and #350 in [DifferentialDrive.java](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java) is where `WPI_TalonSRX.set()` is called. This is where I presume we will call `WPI_TalonSRX.set( ControlMode mode, double value)` (i.e. send the control mode with the value to set to). 

This leads me to believe that the mode can not be set once and forgotten about. I could be wrong but I think if you want it to be in Velocity mode, you have to send it with `set()` each call. The [user guide](https://www.ctr-electronics.com/Talon%20SRX%20User's%20Guide.pdf) doesn't say anything about setting these [Control Modes](http://www.ctr-electronics.com/downloads/api/java/html/enumcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1_control_mode.html).

This also leads me to believe that you have to call `follow()` each time the signal changes to the master controllers. 

Hope this helps.

**Comment by jtechau** [comment]
The `set(double)` method in [WPI_TalonSRX.java](https://github.com/CrossTheRoadElec/Phoenix-api/blob/5da24d17adc9db5fd2564453a0649254e8834a10/java/src/com/ctre/phoenix/motorcontrol/can/WPI_TalonSRX.java#L44) explicitly sets the ControlMode to PercentOutput.  Looking at the class hierarchy, I don't see a way to set ControlMode without calling some variation of `set()`.  So I doubt we'll be able to use `DifferentialDrive` with closed-loop control.

That said, there's no compelling reason to use `DifferentialDrive` in tankDrive mode (IMO), as the `tankDrive()` implementation seems trivial.  We can skip the call to `DifferentialDrive.tankMode()` and/or implement our own tankDrive().  This would allow us to use percent-based drive, closed-loop control, or some combination thereof.

Also, I just noticed the earlier comment about using arcade and/or cheesy drive.  I'm not sure we have any use case for those drive modes?  They're typically intended to be used with a steering wheel and throttle control rather than left/right sticks.  Those modes can be used with a gaming controller, although I suspect that might be cumbersome.

**Comment by isaiah-sczbecki** [comment]
Cheesy drive and arcade drive have so far tested extremely positively on a
controller. Currently the drive train toggles between the two modes, with
arcade being a more precise option for turning in place. On a controller,
it feels like playing a first person shooter video game, with left stick
being forward and back on the Y axis, and right stick being turning on the
X axis. The controls are very familiar for most people, more so than tank
controls.

~Isaiah Sczbecki

**Comment by jtechau** [comment]
I guess I shouldn't be surprised by that.

So we can use DifferentialDrive for general.  It would still be interesting to see how much of an advantage we can get from closed-loop control, for fine robot positioning.  I can't think of an easy way to overcome stiction effects in up-close maneuvering with percentage-based control, whereas speed-based control inherently compensates for stiction and similar effects.  If closed-loop control gives better precision at low (start/stop) speeds, it should be simple enough to toggle the controls for precision maneuvering vs quick/intuitive control.

**Comment by jtechau** [comment]
Drive train has been implemented.  Future enhancements can be added as a separate issue.
