### ISSUE TITLE
Update installation wiki

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2019#22]
In light of Issue #20, the [installation wiki page](../wiki/FRC-2019-Development-Environment-Installation) should be reviewed to ensure that it's up to date with all necessary steps.
The wiki page should also include all necessary information for downloading and installation, such as required login information, NI serial number, etc.

Related issues: #2

**Comment by DylanTran71** [comment]
As of 1/10/19, I updated the wiki in which the instructions should lead to a initial working robot build.
