### ISSUE TITLE
Review PixyCam vision processing features

### ISSUE THREAD

**Issue by jv65537** [AGHSEagleRobotics/frc1388-2019#24]
According to the information on the AndyMark web site 6, the PixieCam does both the acquisition and the processing of the image.

Pixy CMUcam5 Image Sensor is a fast vision sensor you can quickly “teach” to find objects. It connects directly to Arduino and other controllers. Pixy pairs a powerful dedicated processor and image sensor. Pixy processes images from the image sensor and only sends the useful information (e.g. purple dinosaur detected at x=54, y=103) to your microcontroller. The information is available through one of several interfaces: UART serial, SPI, I2C, USB, or digital/analog output so your Arduino or other microcontroller can talk easily with Pixy and still have plenty of CPU available for other tasks.

This means it will indeed connect directly to the RoboRio, but only send target location information.

Links:

https://www.chiefdelphi.com/t/how-to-use-the-pixy/153867

https://docs.pixycam.com/

**Comment by Team1388Programming** [comment]
dont have a pixy cam
