### ISSUE TITLE
Elevator Subsystem

### ISSUE THREAD

**Issue by DillonRego** [AGHSEagleRobotics/frc1388-2019#33]
Import last years elevator and update it to work for this years bot

**Comment by jtechau** [comment]
Last year's code was imported to Elevator branch.
Elevator branch was old and had other changes, so elevator code was moved to Elevator2 branch.
Some updates have been made for this year's robot.
Constraints have been added to avoid the tower leaning back while the elevator is too low.
There are still some final changes to be made based on this year's robot, and the code needs to be reviewed.
