### ISSUE TITLE
Update Radio firmware

### ISSUE THREAD

**Issue by Team1388Programming** [AGHSEagleRobotics/frc1388-2019#34]
Radio Configuration Tool Update: An updated version of the FRC Radio Configuration Utility (19.1.1) (https://firstfrc.blob.core.windows.net/frc2019/Radio/FRC_Radio_Configuration_19_1_1.zip ) has been
posted  in the Screensteps Programming your radio article ( https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/144986-programming-your-radio ). This version corrects an issue with
applying the Bandwidth Limit. Teams testing camera streams are advised to update and re-program their radios
(there is no need to re-flash firmware).

- [ ] ~~Knightmare~~
- [ ] ~~Jolt~~
- [ ] ~~TestBoard~~
- [x] (new robot) #

**Comment by jtechau** [comment]
The 2019 radio has been configured.  Others are working as is.
