### ISSUE TITLE
Mutually exclusive: Ball Grabber vs Hatch Cover

### ISSUE THREAD

**Issue by jv65537** [AGHSEagleRobotics/frc1388-2019#39]
Josiah noticed an issue that when the hatch cover arm is active (PancakeMaker), the BallGrabber needs to be open and not active.  i.e., can't grab. can't eject. And vice versa. When BallGrabber is active, We need to not deploy the arm or trigger the hatch cover shooter (eject). 

When Pancake Make is active, disable all BallGrabber functions.
When BallGrabber is active, disable all Pancake Make functions.

need to consider:
- what is the best way to keep these two subsystems from conflicting? 
- state (such as grabber open or hatch arm down) or sensors (prox sensor detects ball or hatch) is better than relying on operator to click a button or make the right decision.

**Comment by jtechau** [comment]
Perhaps this should be one subsystem?

**Comment by DylanTran71** [comment]
This issue was fixed by combining both subsystems (PancakeMaker and BallGrabber) into one subsystem called Manipulator. It also uses one command called Manipulate (which combined both pancakeMake and ballGrab command classes together).
