### ISSUE TITLE
PancakeMaker Subsystem

### ISSUE THREAD

**Issue by DillonRego** [AGHSEagleRobotics/frc1388-2019#40]
Working to create the PancakeMaker Subsystem, and PancakeMake command class.

**Comment by DylanTran71** [comment]
The PancakeMaker subsystem and the pancakeMake command was merged together with the BallGrabber subsystem and ballGrab command, under one Manipulator subsystem and Manipulate class.

The PancakeMaker and pancakeMake code was transferred over. Currently as of writing this, the PancakeMaker is a single-acting solenoid that works with the vertical D-pad buttons (up/down). The physical pancake arm would be started at being at an up position. Pressing the down D-pad button will bring it down, and pressing D-pad up will bring it back up.
