### ISSUE TITLE
Auto-align strategy

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2019#8]
Determine a strategy for aligning the robot to a Game Piece placement/retrieval point (i.e. rocket, cargo ship or loading station).  This could be based on vision targets (#5), alignment lines (#6), physical alignment (such as an alignment jig on the manipulator(s)), or other.

Robot alignment with targets is very important, for the following reasons:
1. Game time is limited
1. Scoring requires many Game Pieces to be placed in a match
1. Game Pieces (both Cargo and Hatch Panels) have a relatively small placement tolerance
1. Drivers generally have a difficult time manually aligning the robot precisely, requiring a significant amount of time

An auto-alignment strategy should allow the drive team to place the robot near the target in a minimal amount of time.

**Comment by jtechau** [comment]
An example:
The robot could have light sensors at the center of rotation (mid-point between center wheels on a West Coast (aka tank) drive), and one near the front center of the robot.  If the driver approaches an Alignment Line at an angle and engages the auto-align feature, the robot could move forward until the first sensor passes the Line, slows and stops when the mid-point sensor hits the line, then rotates until the front sensor crosses the line.  The robot should now be aligned with the target.

Note that this strategy is just an example, and probably wouldn't work since the Alignment Line is presumably shorter than the distance from the face of the target to the mid-point of the robot.

**Comment by jtechau** [comment]
Possible strategy, using light sensors and Alignment Line:
The driver approaches the target, stopping at/near the face of the target and approximately aligned.  The robot could back up first with the left wheels, and sense the position of the line with two light sensors positioned on the center line of the robot (one in front of the other).  Then back up only using the right wheel to further refine the Line position (or find it, if the first step failed to find it).  Now that the position of the robot relative to the Line is known, navigate the robot to achieve alignment with the target.

**Comment by zerovectorspace** [comment]
I'm not familiar with vision systems but expanding on the light sensors (photoresistors) mounted to bottom of the robot:

Could we create a line of photoresistors placed on the x-axis? This would allow us to quickly determine if the robot needs to backup or move forward?

If the number of photoresistors is unbounded, we may be able to place them along the x and y axes to determine the exact location of the center line.

**Comment by jtechau** [comment]
Great question.  There are a couple practical limits to the number of photosensors we can use.  First is price. It's been a while since I've looked into it, but quality sensors aren't cheap.  The second constraint is that each sensor will generally require an input on the RoboRIO, and those are limited.

That said, there may be other solutions that are more cost effective and/or use fewer inputs to the RoboRIO.  If anyone finds something, we can discuss it.
